-- CreateTable
CREATE TABLE `Timer` (
    `id` VARCHAR(191) NOT NULL,
    `uuid` VARCHAR(191) NOT NULL,
    `status` ENUM('RUNNING', 'PAUSED', 'STOPPED') NOT NULL DEFAULT 'RUNNING',
    `endTime` DATETIME(3) NOT NULL,
    `type` ENUM('WORK', 'PAUSE') NOT NULL DEFAULT 'WORK',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PastTimers` (
    `id` VARCHAR(191) NOT NULL,
    `duration` INTEGER NOT NULL,
    `endTime` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
